//! Steane-code (7,4) error-correcting code for kernel consciousness state.
//!
//! Protects the SelfModel serialized buffer against single-bit flips (hardware
//! fault, DRAM error, intentional bit-twiddling). Uses the classical [7,4,3]
//! Hamming code (a degenerate Steane code over GF(2)):
//!
//!   - 4 data bits → 7 code bits (3 parity bits appended)
//!   - Detects all 1-bit and 2-bit errors; corrects all 1-bit errors.
//!   - Encode: 71-byte buffer → 142 7-bit codewords (stored as 142 bytes, top bit unused)
//!   - Decode: correct in-place, return number of bits repaired.
//!
//! Parity check matrix H (standard [7,4,3] Hamming):
//!   p1 covers bits {1,3,5,7} → positions 0,2,4,6 (0-indexed)
//!   p2 covers bits {2,3,6,7} → positions 1,2,5,6
//!   p4 covers bits {4,5,6,7} → positions 3,4,5,6
//!
//! Generator/encode: given nibble d = [d0 d1 d2 d3]:
//!   c[0]=d0, c[1]=d1, c[2]=d2, c[3]=d3
//!   c[4] = d0 ^ d1 ^ d2   (p1)
//!   c[5] = d0 ^ d1 ^ d3   (p2)
//!   c[6] = d0 ^ d2 ^ d3   (p4)

/// Encode a 4-bit nibble into a 7-bit Hamming codeword (stored in bits 6:0 of a u8).
#[inline(always)]
fn encode_nibble(d: u8) -> u8 {
    let d0 = (d >> 0) & 1;
    let d1 = (d >> 1) & 1;
    let d2 = (d >> 2) & 1;
    let d3 = (d >> 3) & 1;
    let p1 = d0 ^ d1 ^ d2;
    let p2 = d0 ^ d1 ^ d3;
    let p4 = d0 ^ d2 ^ d3;
    d0 | (d1 << 1) | (d2 << 2) | (d3 << 3) | (p1 << 4) | (p2 << 5) | (p4 << 6)
}

/// Decode a 7-bit Hamming codeword, correct a single-bit error in-place.
/// Returns the corrected 4-bit nibble.
#[inline(always)]
fn decode_codeword(mut c: u8) -> (u8, bool) {
    let bit = |i: u32| (c >> i) & 1;

    // Syndrome: s1=p1 check, s2=p2 check, s4=p4 check
    let s1 = bit(0) ^ bit(1) ^ bit(2) ^ bit(4);
    let s2 = bit(0) ^ bit(1) ^ bit(3) ^ bit(5);
    let s4 = bit(0) ^ bit(2) ^ bit(3) ^ bit(6);
    let syndrome = s1 | (s2 << 1) | (s4 << 2); // 0 = no error; 1-7 = error position (1-indexed)

    let repaired = syndrome != 0;
    if repaired && syndrome <= 7 {
        // Flip the erroneous bit (syndrome is 1-indexed position)
        c ^= 1 << (syndrome - 1);
    }

    let nibble = c & 0x0F; // data bits are in positions 0-3
    (nibble, repaired)
}

/// Encode `data` bytes into a Hamming ECC buffer.
/// Output length = `data.len() * 2` (two 7-bit codewords per byte, one per nibble).
pub fn encode(data: &[u8], out: &mut alloc::vec::Vec<u8>) {
    out.clear();
    out.reserve(data.len() * 2);
    for &byte in data {
        out.push(encode_nibble(byte & 0x0F));       // low nibble
        out.push(encode_nibble((byte >> 4) & 0x0F)); // high nibble
    }
}

/// Verify and repair `data` in-place using the ECC buffer generated by `encode`.
/// Returns `(errors_detected, bits_repaired)`.
/// If `ecc.len() != data.len() * 2` the check is skipped (returns (false, 0)).
pub fn verify_and_repair(data: &mut [u8], ecc: &[u8]) -> (bool, u32) {
    if ecc.len() != data.len() * 2 {
        return (false, 0);
    }

    let mut any_error = false;
    let mut repaired = 0u32;

    for (i, byte) in data.iter_mut().enumerate() {
        let lo_cw = ecc[i * 2];
        let hi_cw = ecc[i * 2 + 1];

        // Reconstruct what the codewords should look like for the current byte.
        let expected_lo = encode_nibble(*byte & 0x0F);
        let expected_hi = encode_nibble((*byte >> 4) & 0x0F);

        let lo_mismatch = lo_cw != expected_lo;
        let hi_mismatch = hi_cw != expected_hi;

        if lo_mismatch {
            any_error = true;
            let (corrected_nibble, fixed) = decode_codeword(lo_cw);
            if fixed {
                *byte = (*byte & 0xF0) | (corrected_nibble & 0x0F);
                repaired += 1;
            }
        }
        if hi_mismatch {
            any_error = true;
            let (corrected_nibble, fixed) = decode_codeword(hi_cw);
            if fixed {
                *byte = (*byte & 0x0F) | ((corrected_nibble & 0x0F) << 4);
                repaired += 1;
            }
        }
    }

    (any_error, repaired)
}

/// Compact self-test: encode a known pattern, flip one bit, verify repair.
/// Returns true if the codec is working correctly.
#[allow(dead_code)]
pub fn self_test() -> bool {
    let data: &[u8] = &[0xA5, 0x3C, 0xFF, 0x00, 0x12, 0x34, 0x56, 0x78];
    let mut ecc = alloc::vec::Vec::new();
    encode(data, &mut ecc);

    // Flip bit 2 of the first codeword
    let mut corrupted = data.to_vec();
    corrupted[0] ^= 0x01; // flip low bit of first byte

    let (err, fixed) = verify_and_repair(&mut corrupted, &ecc);
    err && fixed == 1 && corrupted == data
}
